# Generated by Django 5.2.4 on 2025-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True),
        ),
    ]
