# Generated by Django 5.2.4 on 2025-07-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_booking_google_calendar_event_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('session_date', 'session_time')},
        ),
    ]
