# Generated by Django 5.2.4 on 2025-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('reschedule', 'Reschedule'), ('refund', 'Refund'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
