# Generated by Django 5.2.4 on 2025-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_calendar_event_id',
            field=models.CharField(blank=True, help_text='Admin event ID in Google Calendar', max_length=255, null=True),
        ),
    ]
