# Generated by Django 5.2.4 on 2025-07-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_booking_admin_calendar_event_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
