# Generated by Django 5.2.4 on 2025-07-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_admin_slot',
            field=models.BooleanField(default=False, help_text='Is this booking an Admin slot?'),
        ),
    ]
