# Generated by Django 5.2.4 on 2025-07-17 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_booking_is_admin_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('product', 'session_date', 'session_time', 'is_admin_slot'), name='unique_booking_per_type_per_slot'),
        ),
    ]
